import { copyFile, mkdir, writeFile } from "node:fs/promises";
import { PUBLIC_CONFIG } from "../../src/config/config.ts";

const { clientIcons, design } = PUBLIC_CONFIG.frontend;
const output = new URL("../public/icons/", import.meta.url);
await mkdir(output, { recursive: true });
for (const file of new Set(Object.values(clientIcons))) {
  await copyFile(
    new URL(`../assets/icons/${file}`, import.meta.url),
    new URL(file, output),
  );
}
const tokens = Object.entries(design.colors).map(
  ([key, value]) => `--${key}: ${value};`,
);
tokens.push(
  `--body-size: ${design.bodyPx}px;`,
  `--evidence-size: ${design.evidencePx}px;`,
  `--control-size: ${design.controlPx}px;`,
  `--client-icon-size: ${design.iconPx}px;`,
);
await writeFile(
  new URL("../app/design.generated.css", import.meta.url),
  `/* Generated by scripts/prepare-assets.mjs. */\n:root { ${tokens.join(" ")} }\n` +
    `@media (min-width: ${design.comparisonPx}px) { .attempt-choices { grid-template-columns: repeat(2, minmax(0, 1fr)); } }\n` +
    `@media (max-width: ${design.narrowPx}px) { .connection-main { grid-template-columns: 46px minmax(0, 1fr); } .connection-main > .status-badge { grid-column: 2; margin: 0; } .connection-row { grid-template-columns: minmax(0, 1fr); } .connection-action { grid-column: 1; grid-row: auto; margin: 16px 0 0 60px; } .profile-summary { grid-template-columns: 64px minmax(0, 1fr); } .profile-summary > .status-badge { grid-column: 2; justify-self: start; } .sign-in-layout { grid-template-columns: minmax(0, 1fr); } }\n` +
    `@media (max-width: ${design.compactPx}px) { .connections-toolbar { flex-direction: column; } .connection-filter select { width: 100%; max-width: none; } .consent-actions { grid-template-columns: minmax(0, 1fr); } .client-setup-tabs [role=tablist] { height: auto; flex-wrap: wrap; } }\n`,
);
